language: ruby
sudo: false
dist: trusty
cache: bundler
rvm:
  - 2.5
  - jruby
  - ruby-head
  - jruby-head
jdk:
  - openjdk8
  - oraclejdk8
matrix:
  exclude:
    - rvm: 2.5
      jdk: oraclejdk8
    - rvm: ruby-head
      jdk: oraclejdk8
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
branches:
  only:
      - master
      - v2
before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -y -q
  - sudo apt-get install -y -q ffmpeg gstreamer0.10-ffmpeg
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade --ignore-installed opf-fido six
  - sudo wget -O droid.zip -q http://www.nationalarchives.gov.uk/documents/information-management/droid-binary-6.4-bin.zip
  - sudo mkdir -p /opt/droid
  - sudo unzip droid.zip -d /opt/droid
  - sudo chmod 755 /opt/droid/droid.sh
  - sudo locale-gen "en_US.UTF-8"
  - echo 'Europe/Brussels' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
env:
  - LC_ALL=en_US.UTF-8
  - LANG=en_US.UTF-8
addons:
  apt:
    packages:
      - python2.7
      - imagemagick
      - libreoffice
      - ghostscript
      - sox
      - libsox-dev
      - libsox-fmt-all
      - libchromaprint-dev
      - libchromaprint-tools
