language: ruby
sudo: false
dist: trusty
cache: bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-9.1
  - jruby-head
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
matrix:
  exclude:
    - rvm: 2.3
      jdk: openjdk10
    - rvm: 2.3
      jdk: openjdk11
    - rvm: 2.4
      jdk: openjdk10
    - rvm: 2.4
      jdk: openjdk11
    - rvm: 2.5
      jdk: openjdk10
    - rvm: 2.5
      jdk: openjdk11
    - rvm: 2.6
      jdk: openjdk10
    - rvm: 2.6
      jdk: openjdk11
    - rvm: ruby-head
      jdk: openjdk10
    - rvm: ruby-head
      jdk: openjdk11
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
branches:
  only:
      - master

env:
  - LC_ALL=en_IE.UTF-8

before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -y -q
  - sudo apt-get install -y -q ffmpeg gstreamer0.10-ffmpeg
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade --ignore-installed opf-fido six
  - sudo wget -O droid.zip -q http://www.nationalarchives.gov.uk/documents/information-management/droid-binary-6.4-bin.zip
  - sudo mkdir -p /opt/droid
  - sudo unzip droid.zip -d /opt/droid
  - sudo chmod 755 /opt/droid/droid.sh
  - sudo locale-gen "en_US.UTF-8"
  - sudo dpkg-reconfigure locales
  - echo "8\n9\n" | sudo dpkg-reconfigure tzdata
addons:
  apt:
    packages:
      - python2.7
      - imagemagick
      - libreoffice
      - ghostscript
      - sox
      - libsox-dev
      - libsox-fmt-all
      - libchromaprint-dev
      - libchromaprint-tools
